name: Beta Release

on:
  push:
    tags:
      - '*-beta.*'
      - '*-beta'
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      NAME: Task Concentrator BETA
      TAG_NAME: ${{ github.ref_name }}
      DESCRIPTION: THIS EXTENSION IS FOR BETA TESTING
    steps:
      - uses: actions/checkout@v4
      - name: Get branch name
        run: |
          BRANCH=$(git branch -r --contains ${{ github.ref }} --format "%(refname:lstrip=3)")
          git branch -r --contains ${{ github.ref }}
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "Branch is $BRANCH"
      - name: Check if branch is main
        run: |
          echo "Branch is $BRANCH"
          if [ "$BRANCH" != "main" ]; then
            echo "This tag is not on the main branch. Exiting."
            exit 1
          fi
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock
      - run: yarn install --immutable
      - name: Extract Version
        run: |
          # Remove 'v' prefix and anything after a hyphen
          VERSION=$(echo "${{ env.TAG_NAME }}" | sed -E 's/^v//; s/-.*//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build
        run: yarn build
      - name: Compress
        run: |
          mv dist task-concentrator
          zip -r task-concentrator-${{ env.TAG_NAME  }}.zip task-concentrator
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME  }}
          files: task-concentrator-${{ env.TAG_NAME  }}.zip
          prerelease: true
          fail_on_unmatched_files: true
